export const properties = [
  {
    id: 'vND7cbUtdj4CYmMpJwPh',
    images: [
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961418/homely/property-a.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-2.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-3.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-4.jpg',
    ],
    title: 'Lafontaine 124',
    address: 'Polanco, Ciudad de México',
    price: '6,500,000',
    area: '60',
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    amenities: ['Gimnasio', 'Piscina', 'Bar', 'Cancha de tenis'],
    status: 'sale',
    type: 'department',
    delivery: 'enero 2024',
  },
  {
    id: 'npJmqBW6rvCs9gAyUdF3',
    images: [
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961418/homely/property-b.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-2.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-3.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-4.jpg',
    ],
    title: 'Leibnitz 273',
    address: 'Anzures, Ciudad de México',
    price: '8,700,000',
    area: '80',
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    amenities: ['Gimnasio', 'Piscina', 'Bar', 'Cancha de tenis'],
    status: 'sale',
    type: 'house',
    delivery: 'febrero 2024',
  },
  {
    id: 'YUbz9fRgcTmhAWQEq74a',
    images: [
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961418/homely/property-c.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-2.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-3.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-4.jpg',
    ],
    title: 'Torre de la Alameda',
    address: 'Roma, Ciudad de México',
    price: '7,600,000',
    area: '70',
    bedrooms: 2,
    bathrooms: 2,
    parking: 2,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    amenities: ['Gimnasio', 'Piscina', 'Bar', 'Cancha de tenis'],
    status: 'sale',
    type: 'department',
    delivery: 'marzo 2024',
  },
  {
    id: 'PcDRuFxN7rkAs536jqHE',
    images: [
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961418/homely/property-d.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-2.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-3.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-4.jpg',
    ],
    title: 'Fernando Montes de Oca 43',
    address: 'Condesa, Ciudad de México',
    price: '9,800,000',
    area: '90',
    bedrooms: 2,
    bathrooms: 2,
    parking: 2,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    amenities: ['Gimnasio', 'Piscina', 'Bar', 'Cancha de tenis'],
    status: 'sale',
    type: 'house',
    delivery: 'abril 2024',
  },
  {
    id: 'MJUEVACsXz2n6vWR3mxt',
    images: [
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961418/homely/property-e.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-2.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-3.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-4.jpg',
    ],
    title: 'Punta del Este',
    address: 'Santa Fe, Ciudad de México',
    price: '5,400,000',
    area: '50',
    parking: 1,
    elevator: true,
    security: true,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    amenities: ['Restaurante', 'Terraza', 'Gimnasio'],
    status: 'sale',
    type: 'office',
    delivery: 'mayo 2024',
  },
  {
    id: 'nEXAF6kbG5sWwB8ThqfC',
    images: [
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961418/homely/property-f.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-2.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-3.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-4.jpg',
    ],
    title: 'Goldsmith 309',
    address: 'Polanco, Ciudad de México',
    price: '15,400',
    area: '50',
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    amenities: ['Gimnasio', 'Piscina', 'Bar', 'Cancha de tenis'],
    status: 'rent',
    type: 'department',
    delivery: 'inmediata',
  },
  {
    id: 'DHwkuG59C3zB8ygaqLW7',
    images: [
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961418/homely/property-h.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-2.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-3.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-4.jpg',
    ],
    title: 'Valladolid 289',
    address: 'Roma, Ciudad de México',
    price: '17,600',
    area: '70',
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    amenities: ['Gimnasio', 'Piscina', 'Bar', 'Cancha de tenis'],
    status: 'rent',
    type: 'house',
    delivery: 'inmediata',
  },
  {
    id: 'wyRtJDubhgXz5c4nv7Km',
    images: [
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961418/homely/property-i.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-2.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-3.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-4.jpg',
    ],
    title: 'Juan de la Barrera 599',
    address: 'Condesa, Ciudad de México',
    price: '16,500',
    area: '60',
    bedrooms: 2,
    bathrooms: 2,
    parking: 2,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    amenities: ['Gimnasio', 'Piscina', 'Bar', 'Cancha de tenis'],
    status: 'rent',
    type: 'department',
    delivery: 'agosto 2023',
  },
  {
    id: 'DjqYKGZ4HmR9azXb6pU7',
    images: [
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961418/homely/property-j.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-2.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-3.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-4.jpg',
    ],
    title: 'Calle de los Ángeles 307',
    address: 'Santa Fe, Ciudad de México',
    price: '18,700',
    area: '80',
    bedrooms: 2,
    bathrooms: 2,
    parking: 2,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    amenities: ['Gimnasio', 'Piscina', 'Bar', 'Cancha de tenis'],
    status: 'rent',
    type: 'house',
    delivery: 'inmediata',
  },
  {
    id: 'BRd5Mg2KHwEU6S8LfWYX',
    images: [
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961418/homely/property-g.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-2.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-3.jpg',
      'https://res.cloudinary.com/dlomynswh/image/upload/v1656961416/homely/property-4.jpg',
    ],
    title: 'Gutenberg Work Center',
    address: 'Anzures, Ciudad de México',
    price: '14,300',
    area: '40',
    parking: 2,
    elevator: true,
    security: true,
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    amenities: ['Restaurante', 'Terraza', 'Gimnasio'],
    status: 'rent',
    type: 'office',
    delivery: 'inmediata',
  },
];
