import PropertiesContainer from '@/components/properties-container';
import Head from 'next/head';

export default function Houses({ data }) {
  return (
    <>
      <Head>
        <title>Casas | Homely</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <PropertiesContainer data={data} title="Casas" />
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch(`${process.env.API_URL}/api/properties?type=house`);
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}
