import Features from '@/components/features';
import Hero from '@/components/hero';
import LatestProperties from '@/components/latest-properties';
import Head from 'next/head';
import useSWR from 'swr';

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Home() {
  const { data, error, isLoading } = useSWR('/api/latest', fetcher);

  return (
    <>
      <Head>
        <title>Homely</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Hero />
      <LatestProperties data={data} error={error} isLoading={isLoading} />
      <Features />
    </>
  );
}
