import Features from '@/components/features';
import Hero from '@/components/hero';
import LatestProperties from '@/components/latest-properties';
import Head from 'next/head';

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Homely</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        <Hero />
        <LatestProperties data={data} />
        <Features />
      </div>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch(`${process.env.API_URL}/api/latest`);
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}
