import PropertiesContainer from '@/components/properties-container';
import Head from 'next/head';

export default function Rent({ data }) {
  return (
    <>
      <Head>
        <title>Propiedades en renta | Homely</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <PropertiesContainer data={data} title="Propiedades en renta" />
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch(`${process.env.API_URL}/api/properties?status=rent`);
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}
