import PropertiesContainer from '@/components/properties-container';
import Head from 'next/head';
import useSWR from 'swr';

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Rent() {
  const { data, error, isLoading } = useSWR(
    '/api/properties?status=rent',
    fetcher
  );

  return (
    <>
      <Head>
        <title>Propiedades en renta | Homely</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <PropertiesContainer
        data={data}
        error={error}
        isLoading={isLoading}
        title="Propiedades en renta"
      />
    </>
  );
}
