import PropertyInfo from '@/components/property-info';
import Head from 'next/head';
import { useRouter } from 'next/router';
import useSWR from 'swr';

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Property() {
  const { id } = useRouter().query;
  const { data, error, isLoading } = useSWR(`/api/property/${id}`, fetcher);

  if (error) return <div>Failed to load</div>;
  if (!data) return <div>Loading...</div>;

  return (
    <>
      <Head>
        <title>{`${data.title} | Homely`}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <PropertyInfo data={data} error={error} isLoading={isLoading} />
    </>
  );
}
