import PropertyInfo from '@/components/property-info';
import Head from 'next/head';
import { useEffect, useState } from 'react';

export default function Property({ paramsId }) {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);
  const [isLoading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);
    fetch(`/api/property/${paramsId}`)
      .then((res) => res.json())
      .then((data) => {
        setData(data);
        setLoading(false);
      })
      .catch((err) => {
        setError(err);
        setLoading(false);
      })
      .finally(() => {
        setLoading(false);
      });
  }, [paramsId]);

  if (!data) return <></>;

  return (
    <>
      <Head>
        <title>{`${data.title} | Homely`}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <PropertyInfo data={data} error={error} isLoading={isLoading} />
    </>
  );
}

export const getServerSideProps = async (context) => {
  return { props: { paramsId: context.params.id } };
};
