import PropertyInfo from '@/components/property-info';
import Head from 'next/head';

export default function Property({ data }) {
  const { title } = data;

  return (
    <>
      <Head>
        <title>{`${title} | Homely`}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <PropertyInfo data={data} />
    </>
  );
}

export async function getStaticPaths() {
  const res = await fetch(`${process.env.API_URL}/api/properties`);
  const data = await res.json();

  const paths = data.map((property) => ({
    params: { id: property.id },
  }));

  return { paths, fallback: false };
}

export async function getStaticProps({ params }) {
  const res = await fetch(`${process.env.API_URL}/api/property/${params.id}`);
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}
